langauge: c
env:
  - RACKET_VERSION=6.1.1

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

script:
 - /usr/racket/bin/raco pkg install $TRAVIS_BUILD_DIR
 - /usr/racket/bin/raco test
 - /usr/racket/bin/raco coverage -c coveralls
